### ISSUE TITLE
Service Not Started Kill App and Again Open - Android

### ISSUE THREAD

**Issue by DaxeshKhatri** [vmware-tanzu/gimbal#278]
I have make demo with sdk into ReactNative by using native bridging. It is working when app install first time. But When i will kill app from stack and again open app index file run and call native method for start gimble  and method is call from native but not detecting any method of placemanager.

i show log in android studio that Failed to update places: Unable to refresh place bubble, not fix available. is it Issue or other ?

i'm stuck from 2 days and now i'm questing about the SDK. please help asap so i can give better resolution to client.

**Comment by stevesloka** [comment]
Hey @DaxeshKhatri I don't think you have the proper repo. This repo is a networking repo for Kubernetes & Contour. Can you please double-check?
